### ISSUE TITLE
how to run the skybook.nim

### ISSUE THREAD

**Issue by Tback1** [muxueqz/skybook#1]
我设定好了nim环境与jester支持，也编译成功了skybook.exe文件
运行正常

INFO Jester is making jokes at http://127.0.0.1:5000
DEBUG GET /
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
DEBUG GET /favicon.ico
DEBUG   404 Not Found {"content-type": @["text/html;charset=utf-8"]}
DEBUG GET /a
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
DEBUG GET /a
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
DEBUG GET /a
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
DEBUG POST /
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
DEBUG POST /
https://www.google.com/search?q= jester 0.4.1&oq= jester 0.4.1&aqs=heirloom-srp..(url: "https://www.google.com/search?q= jester 0.4.1&oq= jester 0.4.1&aqs=heirloom-srp..", name: "jester 0.4.1 - Google 鎼滅储", note: "", tags: "")
dump full
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
DEBUG GET /a
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
DEBUG POST /
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
DEBUG GET /a
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
DEBUG GET /a
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}

将coffce脚本转换为js脚本后也能正常在浏览器添加书签到数据库

但是如何在浏览器中添加查询的关键字，这个还请说明一下~~谢谢
另外在http://localhost:5000/页面  可以考虑添加一个删除的功能

js书签：
javascript:var description, note, title, url;  title = encodeURIComponent(document.title);  url = encodeURIComponent(location.href);  note = '';  description = document.getElementsByName('description')[0];  if (description) {   note = encodeURIComponent(description.content); }  window.open('http://localhost:5000/a?name=' + title + '&note=' + note + '&url=' + url);

**Comment by muxueqz** [comment]
# 如何添加搜索引擎
在浏览器的设置如，如Chrome： chrome://settings/searchEngines
![image](https://user-images.githubusercontent.com/730639/62471927-44641100-b7d0-11e9-977f-2e9c3271e941.png)

# 关于删除功能
嗯，这确实是我遗漏了（好吧，我得承认我可能根本没想到书签需要删除），之后我加上去吧！

**Comment by muxueqz** [comment]
@Tback1 你后来进展怎么样了呢？如果没问题我就Close这个issue啦

**Comment by muxueqz** [comment]
@Tback1 今天更新的新版本已经支持删除功能（不过页面上暂时是通过一个新页面表单实现的，后续再改成ajax吧）

**Comment by Tback1** [comment]
> @Tback1 beacount好像有些好玩儿呀，5000端口是因为用到的Web框架jester默认是5000……

beacount只要不在Windows下跑，一切都好说~Python在Windows下跑起来，配置个环境每个软件依赖各不相同，真是酸爽~

**Comment by muxueqz** [comment]
> > @Tback1 beacount好像有些好玩儿呀，5000端口是因为用到的Web框架 Jester 默认是5000……
> 
> beacount只要不在Windows下跑，一切都好说 Python在 Windows 下跑起来，配置个环境每个软件依赖各不相同，真是酸爽

哈，这是真的，尤其依赖C模块更是暴爽，不过Win10以后可以跑在Docker里嘛

**Comment by Tback1** [comment]
> > > @Tback1 beacount好像有些好玩儿呀，5000端口是因为用到的Web框架 Jester 默认是5000……
> > 
> > 
> > beacount只要不在Windows下跑，一切都好说 Python在 Windows 下跑起来，配置个环境每个软件依赖各不相同，真是酸爽
> 
> 哈，这是真的，尤其依赖C模块更是暴爽，不过Win10以后可以跑在Docker里嘛

只希望 bug10 哪天能不抽风了，我就从LTSC版本切换到 pro去吧~好歹也有个正版数字激活授权，还天天苦逼LTSC也是被这软件工程质量打败了

**Comment by muxueqz** [comment]
> > > > @Tback1 beacount好像有些好玩儿呀，5000端口是因为用到的Web框架 Jester 默认是5000……
> > > 
> > > 
> > > beacount只要不在Windows下跑，一切都好说 Python在 Windows 下跑起来，配置个环境每个软件依赖各不相同，真是酸爽
> > 
> > 
> > 哈，这是真的，尤其依赖C模块更是暴爽，不过Win10以后可以跑在Docker里嘛
> 
> 只希望 bug10 哪天能不抽风了，我就从LTSC版本切换到 pro去吧~好歹也有个正版数字激活授权，还天天苦逼LTSC也是被这软件工程质量打败了

哈，Linux用户表示帮不上你，我甚至都不知道LTSC是啥，老坛酸菜吗？XD，好啦，开玩笑的，是长期支持版本吧？

**Comment by Tback1** [comment]
> > > > > @Tback1 beacount好像有些好玩儿呀，5000端口是因为用到的Web框架 Jester 默认是5000……
> > > > 
> > > > 
> > > > beacount只要不在Windows下跑，一切都好说 Python在 Windows 下跑起来，配置个环境每个软件依赖各不相同，真是酸爽
> > > 
> > > 
> > > 哈，这是真的，尤其依赖C模块更是暴爽，不过Win10以后可以跑在Docker里嘛
> > 
> > 
> > 只希望 bug10 哪天能不抽风了，我就从LTSC版本切换到 pro去吧~好歹也有个正版数字激活授权，还天天苦逼LTSC也是被这软件工程质量打败了
> 
> 哈，Linux用户表示帮不上你，我甚至都不知道LTSC是啥，老坛酸菜吗？XD，好啦，开玩笑的，是长期支持版本吧？

这么一说 还真是 老坛酸菜~~ 比起发行版本，真是酸爽多了。客官，不来一坛么 🤣~~
